name: forgejo-EditIssue-Test

on:
  workflow_dispatch:

jobs:
  forgejo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Forgejo API Action
        uses: ./
        with:
          api_url: ${{ vars.FORGEJO_API_URL }}
          token: ${{ secrets.FORGEJO_TOKEN }}
          repository: "owner/repo"
          index: 123
          assignees: user1,user2
          body: "This is my issue"
          due_date: 2025-12-24
          milestone: 1
          ref: feat/abc
          state: open
          title: "Test Issue from Action"
          #unset_due_date: true
          #debug: true
